app:
  name: ai-camera-api-cms
  env: development
  debug: true
  secret:
    jwt: aCSnbH6B1ATyRIDkOS3pB9xXMwOza9m7XrPnceNNVXxwvkbqjXwqgTuFgD1j6GsA
  server:
    host: 0.0.0.0
    port: 8000
    log: true
    domain: https://beta.ocopvietnam.gov.vn
    media: https://beta.ocopvietnam.gov.vn
    ai_host: https://14.250.34.245:9101
    version: 2021.10.08.11.35