info:
  contact: { }
paths:
  /api/v1/auth/code-authorization:
    post:
      consumes:
        - application/json
      produces:
        - application/json
      responses:
        "200":
          description: ""
      summary: Lấy token từ code đo keycloak trả về
  /api/v1/auth/oidc:
    get:
      consumes:
        - application/json
      produces:
        - application/json
      responses:
        "200":
          description: ""
      summary: Lấy link OIDC
  /api/v1/common/organization-units:
    get:
      consumes:
        - application/json
      produces:
        - application/json
      responses:
        "200":
          description: ""
      summary: Lấy danh sách đơn vị tổ chức
swagger: "2.0"
